plugins:
  - serverless-dotenv-plugin
  - serverless-domain-manager
  - serverless-offline
  - serverless-apigw-binary
custom:
  apigwBinary:
    types:
      - "*/*"
  customDomain:
    domainName: brz.gg
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateName: brz.gg

service: brz-gg
useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  memorySize: 128
  iam:
    role: arn:aws:iam::408356563302:role/brz_lambda
package:
  excludeDevDependencies: true
  patterns:
    - dist/**
    - lambda.ts
    - package.json
    - yarn.lock
    - '!.cicd/**'
    - '!src/**'
    - '!terraform/**'
    - '!test/**'
    - '!public/**'
    - '!.serverless/**'
functions:
  app:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            origins: 
              - https://brz.gg
      - http:
          method: any
          path: /{any+}
          cors:
            origins: 
              - https://brz.gg