name: Deployment

on:
  push:
    branches:
      - main
    paths:
      - '.cicd/**'
      - '.github/workflows/**'
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'yarn.lock'
      - '*.js'

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
        s3_bucket_name: ${{ steps.get_bucket_name.outputs.stdout }}
        cloudfront_distribution_id: ${{ steps.get_distribution_id.outputs.stdout }}
    steps:
      - name: Clone the repository code
        uses: actions/checkout@v2
      - name: Setup the Terraform CLI
        uses: hashicorp/setup-terraform@v2
      - name: Setup AWS Credentials
        run: |
          mkdir ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          AWS_PROFILE=default && echo AWS_PROFILE=$AWS_PROFILE >> $GITHUB_ENV
      - name: Initialize the Terraform working directory
        working-directory: .cicd/terraform
        id: init
        run: terraform init -input=false
      - name: Apply the Terraform execution plan
        working-directory: .cicd/terraform
        id: plan
        run: terraform apply -no-color -auto-approve
        env:
          TF_VAR_github_pat: ${{ secrets.GH_PAT }}
      - name: get bucket name
        working-directory: .cicd/terraform
        id: get_bucket_name
        run: terraform output --raw s3_bucket_name
      - name: get distribution id
        working-directory: .cicd/terraform
        id: get_distribution_id
        run: terraform output --raw cloudfront_distribution_id

  build_and_sync:
    needs: terraform
    name: Build project and Deploy
    runs-on: ubuntu-latest
    outputs:
        samp_server_ip_address: ${{ needs.terraform.outputs.s3_bucket_name }}
    steps:
      - name: Clone the repository code
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with: 
          node-version: "lts/*"
      - name: Build project
        run: |
          yarn install
          yarn build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
      - name: Sync dist folder to s3
        run: |
          aws s3 sync dist s3://${{ needs.terraform.outputs.s3_bucket_name }} --acl public-read --follow-symlinks --delete
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ needs.terraform.outputs.cloudfront_distribution_id }} --paths "/*"
